global:
  scrape_interval:     1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: ff 
    metrics_path: /metrics
    static_configs:
      - targets:
        - ff:2112